config/routes.rb
AskerRuby::Application.routes.draw do
  resources :users
  resources :questions
  resources :answers, only: [:create, :destroy]
  resources :sessions, only: [:create, :destroy]

  root 'questions#index'

  get '/signin', to: 'users#new'
  delete '/signout', to: 'sessions#destroy'

  get '/pick/:answer_id', to: 'answers#pick_answer', as: 'pick'
  get '/vote_answer/:answer_id/:vote', to: 'answers#vote', as: 'vote_answer'
  get '/vote_question/:question_id/:vote', to: 'questions#vote', as: 'vote_question'

end

app/models/answer.rb
# == Schema Information
#
# Table name: answers
#
#  id          :integer          not null, primary key
#  content     :text
#  votes       :integer          default(0)
#  selected    :boolean          default(FALSE)
#  user_id     :integer
#  question_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :question

  validates :content, presence: true
  validates :user_id, presence: true
  validates :question_id, presence: true

end

app/models/question.rb
# == Schema Information
#
# Table name: questions
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  content    :text
#  votes      :integer          default(0)
#  user_id    :integer
#  created_at :datetime
#  updated_at :datetime
#

class Question < ActiveRecord::Base
  belongs_to :user
  has_many :answers

  validates :title, presence: true
  validates :content, presence: true
  validates :user_id, presence: true

end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  email           :string(255)
#  dispname        :string(255)
#  firstname       :string(255)
#  lastname        :string(255)
#  created_at      :datetime
#  updated_at      :datetime
#  password_digest :string(255)
#  remember_token  :string(255)
#

class User < ActiveRecord::Base
  has_secure_password

  has_many :questions
  has_many :answers

  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token

  VALID_EMAIL_REGEX = /\A[_a-z0-9-]+(\.[_a-z0-9-]+)*@[a-z0-9-]+(\.[a-z0-9-]+)*(\.[a-z]{2,4})\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :dispname, presence: true
  validates :firstname, presence: true
  validates :lastname, presence: true
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true

  def self.search(search)
    if search
      where("dispname LIKE ?", "%#{search}%")
    else
      all
    end
  end

  private
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy, :pick_answer, :vote]

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.build(answer_params)
    @answer.user = current_user
    if @answer.save
      redirect_to @question
    else
      render 'questions/show'
    end
  end

  def destroy
  end

  def pick_answer
    # get picked answer
    answer = Answer.find(params[:answer_id])
    if current_user?(answer.question.user)
      # set selected on other selected answer to false (if exists)
      prev_pick = answer.question.answers.where(selected: true)
      prev_pick.each do |ans|
        ans.update_attributes(selected: false)
      end
      answer.update_attributes(selected: true)
      # redirect to question page
      redirect_to answer.question
    else
      redirect_to root_path
    end
  end

  def vote
    user = current_user
    answer = Answer.find(params[:answer_id])

    vote_string = "#{user.email}_answer_#{answer.id}"
    vote_digest = Digest::MD5.hexdigest vote_string

    # check if cookie exists => user already voted
    if cookies[vote_digest].nil?
      vote = params[:vote]
      if vote == 'up'
        answer.update_attributes(votes: (answer.votes+1))
      elsif vote == 'down'
        answer.update_attributes(votes: (answer.votes-1))
      end

      # set cookie for user vote
      cookies.permanent[vote_digest] = 1
    end

    redirect_to answer.question
  end

  private
  def answer_params
    params.require(:answer).permit(:content)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :vote]

  def index
    qpp = 4 # questions per page
    if params[:order] == "votes"
      @questions = Question.order(votes: :desc).paginate(page: params[:page], per_page: qpp)
    elsif params[:order] == "unanswered"
      @questions = Question.includes(:answers).group('questions.id, answers.id').having('COUNT(answers.id) = 0').references(:answers)
      @questions = @questions.order(created_at: :desc).paginate(page: params[:page], per_page: qpp)
    else
      @questions = Question.order(created_at: :desc).paginate(page: params[:page], per_page: qpp)
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.order(votes: :desc)
  end

  def create
    @question = current_user.questions.build(question_params)
    if @question.save
      redirect_to root_path
    else
      render 'questions/index'
    end
  end

  def vote
    user = current_user
    question = Question.find(params[:question_id])

    vote_string = "#{user.email}_question_#{question.id}"
    vote_digest = Digest::MD5.hexdigest vote_string

    # check if cookie exists => user already voted
    if cookies[vote_digest].nil?
      vote = params[:vote]
      if vote == 'up'
        question.update_attributes(votes: (question.votes+1))
      elsif vote == 'down'
        question.update_attributes(votes: (question.votes-1))
      end

      # set cookie for user vote
      cookies.permanent[vote_digest] = 1
    end

    redirect_to question
  end

  private
  def question_params
    params.require(:question).permit(:title, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_email(params[:session][:email])
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_to user
    else
      render 'users/new'
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :update]
  before_filter :correct_user, only: [:edit, :update]

  def index
    @users = User.search(params[:search]).paginate(page: params[:page], per_page: 9)
  end

  def show
    @user = User.find(params[:id])
  end

  def new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to @user
    else
      render 'new'
    end
  end

  private
  def user_params
    params.require(:user).permit(:email, :dispname, :firstname, :lastname, :password, :password_confirmation)
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_path) unless current_user?(@user)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  # Returns a full title on a per-page basis.
  def full_title(page_title)
    base_title = "Asker"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end

  def add_dots(text, limit)
    if text.length > limit
      "#{text[0..limit]}..."
    else
      text
    end
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def current_user?(user)
    user == current_user
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  # check and redirect

  def signed_in_user
    redirect_to signin_path unless signed_in?
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <p>
    <%= link_to "HOME", root_path %> |
    <%= link_to "ABOUT", '#' %> |
    <%= link_to "CONTACT", '#' %> |
    <%= link_to "TERMS", '#' %>
  </p>
  <p>&copy; Kristian Žarn. All rights reserved.</p>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div id="topHead">
    <%= link_to image_tag("logo.png"), root_path %>
  </div>
  <nav>
    <ul>
      <li><%= link_to "QUESTIONS", root_path %></li>
      <li><%= link_to "USERS", users_path %></li>
      <% if signed_in? %>
        <li><%= link_to "PROFILE", current_user %></li>
        <li><%= link_to "SIGN OUT", signout_path, method: "delete" %></li>
      <% else %>
        <li><%= link_to "SIGN IN", signin_path %></li>
      <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="container">
  <%= render 'layouts/header' %>

  <div id="wrap">
    <%= yield %>
  </div>

  <%= render 'layouts/footer' %>
</div>

</body>
</html>

app/views/questions/index.html.erb
<% provide(:title, 'Questions') %>

<script>enablejs_questions()</script>

<div id="overlay">
  <div id="wrapQuestionForm">
    <%= image_tag "close.png", id: "closeImg" %>
    <p class="formText">What would you like to know?</p>
    <%= form_for(:question, url: questions_path, html: { id: "questionForm" }) do |f| %>
      <p class="formLabel">
        <%= f.label :title, "Title:" %>
        <%= f.text_field :title, class: "inputBorder" %>
        <span class="formError">*Title is required.</span>
      </p>
      <p class="formLabel">
        <%= f.label :content, "Question:" %>
        <%= f.text_area :content, class: "inputBorder" %>
        <span class="formError">*Question is required.</span>
      </p>
      <p class="submitPos">
        <%= f.submit "Post Question", id: "formSubmit" %>
      </p>
    <% end %>
  </div>
</div>

<div id="wrapLeft">
  <nav>
    <ul>
      <li><%= link_to "NEWEST", root_path(order: "newest"), class: "subnav" %></li>
      <li><%= link_to "VOTES", root_path(order: "votes"), class: "subnav" %></li>
      <li><%= link_to "UNANSWERED", root_path(order: "unanswered"), class: "subnav" %></li>
    </ul>
  </nav>

  <div id="questions">
    <% @questions.each do |question| %>
      <div class="qSummary">
        <div class="qStats">
          <div class="qVotes">
            <% str = pluralize(question.votes, "vote").split %>
            <p class="number"><%= str[0] %></p>
            <p class="label"><%= str[1] %></p>
          </div>
          <div class="qAnswers">
            <% str = pluralize(question.answers.count, "answer").split %>
            <p class="number"><%= str[0] %></p>
            <p class="label"><%= str[1] %></p>
          </div>
        </div>
        <div class="qQuestion">
          <%= link_to question.title, question, class: "qTitle" %>
          <p class="qContent"><%= add_dots(question.content, 300) %></p>
          <p class="qAuthor">
            asked on <%= question.created_at.strftime("%d.%m.%Y") %> by
            <%= link_to question.user.dispname, question.user, class: "userLink" %>
          </p>
        </div>
      </div>
    <% end %>
  </div>

  <%= will_paginate @questions, previous_label: "&#x25C0", next_label: "&#x25B6" %>

</div>

<div id="wrapRight">
  <div id="askQuestion">
    <p>Ask Question</p>
  </div>
</div>

app/views/questions/show.html.erb
<% provide(:title, @question.title) %>

<script>enablejs_answers()</script>

<div id="overlay">
  <div id="wrapAnswerForm">
    <%= image_tag "close.png", id: "closeImg" %>
    <p class="formText">Share your knowledge.</p>

    <%= form_for(:answer, url: answers_path, html: { id: "answerForm" }) do |f| %>
      <%= hidden_field_tag "question_id", @question.id %>
      <p class="formLabel">
        <%= f.label :content, "Your answer:" %>
        <%= f.text_area :content, class: "inputBorder" %>
        <span class="formError">*Answer is required.</span>
      </p>
      <p class="submitPos">
        <%= f.submit "Post answer", id: "formSubmit" %>
      </p>
    <% end %>
  </div>
</div>

<p class="title"><%= @question.title %></p>
<div class="questionFrame">
  <div class="votes">
    <%= link_to image_tag('arrow_up.png', class: "arrowImg"),
                vote_question_path(question_id: @question.id, vote: "up") %>
    <p><%= @question.votes %></p>
    <%= link_to image_tag('arrow_down.png', class: "arrowImg"),
                vote_question_path(question_id: @question.id, vote: "down") %>
  </div>
  <div class="frameContent">
    <div class="mainText">
      <% @question.content.split("\n").each do |str| %>
        <p><%= str %></p>
      <% end %>
    </div>
    <p class="author">
      asked on <%= @question.created_at.strftime("%d.%m.%Y") %> by
      <%= link_to @question.user.dispname, @question.user, class: "userLink" %>
    </p>
    <hr>
  </div>
</div>

<div id="middle">
  <p class="title"><%= pluralize(@question.answers.count, "answer") %></p>
  <p id="addAnswer"><span lang="en" id="langAddAns">Add Answer</span></p>
</div>

<% @answers.each do |answer| %>
  <div class="answerFrame">
    <div class="votes">
      <%= link_to image_tag('arrow_up.png', class: "arrowImg"),
                  vote_answer_path(answer_id: answer.id, vote: "up") %>
      <p><%= answer.votes %></p>
      <%= link_to image_tag('arrow_down.png', class: "arrowImg"),
                  vote_answer_path(answer_id: answer.id, vote: "down") %>
      <% if answer.selected %>
        <%= image_tag('ok_green.png', class: "pickAnswerImg") %>
      <% elsif current_user?(@question.user) %>
        <%= link_to image_tag('ok_gray.png', class: "pickAnswerImg"), pick_path(answer_id: answer.id) %>
      <% end %>
    </div>
    <div class="frameContent">
      <div class="mainText">
        <% answer.content.split("\n").each do |str| %>
          <p><%= str %></p>
        <% end %>
      </div>
      <p class="author">
        answered on <%= answer.created_at.strftime("%d.%m.%Y") %> by
        <%= link_to answer.user.dispname, answer.user, class: "userLink" %>
      </p>
      <hr>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>

<div id="searchFrame">
  <%= form_tag users_path, method: 'get' do %>
    <p class="findUsers">
      <%= label_tag :search, "Find Users:" %>
      <%= text_field_tag :search, params[:search], class: "inputBorder" %>
    </p>

    <%= submit_tag "Go", name: nil, id: "goButton", class: "submit" %>
  <% end %>
</div>

<div id="allUsers">
  <% @users.each do |user| %>
    <div class="userFrame">
      <%= image_tag("profile_pic.png") %>
      <p>
        <%= link_to user.dispname, user, class: "userLink" %>
      </p>
      <p><%= "#{user.firstname} #{user.lastname}" %></p>
      <p><%= "#{user.email}" %></p>
    </div>
  <% end %>
</div>

<%= will_paginate @users, previous_label: "&#x25C0", next_label: "&#x25B6" %>

app/views/users/new.html.erb
<% provide(:title, 'Sign in') %>

<script>enablejs_signin()</script>

<div id="signIn" class="frame">
  <p class="frameHead">Sign in</p>
  <%= form_for(:session, url: sessions_path, html: {id: "signInForm"}) do |f| %>
    <p class="frameLabel">
      <%= f.label :email, "Email:" %>
      <%= f.text_field :email, class: "inputField" %>
      <span class="formError">*Enter a valid email address.</span>
    </p>
    <p class="frameLabel">
      <%= f.label :password, "Password:" %>
      <%= f.password_field :password, class: "inputField" %>
      <span class="formError">*Enter your password.</span>
    </p>
    <p class="buttonPos">
      <%= f.submit "Sign in", id: "signInButt", class: "submit" %>
    </p>
  <% end %>
</div>

<div id="createAccount" class="frame">
  <p class="frameHead">Create new account</p>

  <%= form_for(:user, url: users_path, html: {id: "createAccountForm"}) do |f| %>
    <p class="frameLabel">
      <%= f.label :email, "Email:" %>
      <%= f.text_field :email, class: "inputField" %>
      <span class="formError">*Enter a valid email address.</span>
    </p>
    <p class="frameLabel">
      <%= f.label :dispname, "Displayed Name:" %>
      <%= f.text_field :dispname, class: "inputField" %>
      <span class="formError">*Displayed name is required.</span>
    </p>
    <p class="frameLabel">
      <%= f.label :firstname, "First Name:" %>
      <%= f.text_field :firstname, class: "inputField" %>
      <span class="formError">*First name is required.</span>
    </p>
    <p class="frameLabel">
      <%= f.label :lastname, "Last Name:" %>
      <%= f.text_field :lastname, class: "inputField" %>
      <span class="formError">*Last name is required.</span>
    </p>
    <p class="frameLabel">
      <%= f.label :password, "Password:" %>
      <%= f.password_field :password, class: "inputField" %>
      <span class="formError">*Minimum length of 6.</span>
    </p>
    <p class="frameLabel">
      <%= f.label :password_confirmation, "Confirm Password:" %>
      <%= f.password_field :password_confirmation, class: "inputField" %>
      <span class="formError">*Passwords don't match.</span>
    </p>
    <p class="frameLabel">
      <%= check_box_tag :terms %>
      <%= label_tag :terms, "I agree to the terms and conditions." %>
      <span class="formError termsError">*You have to agree to the terms and conditions.</span>
    </p>
    <p class="buttonPos">
      <%= f.submit "Create my account", id: "CreateButt", class: "submit" %>
    </p>
  <% end %>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.dispname) %>
<div id="profile_user">
  <h2 class="profileTitle"><%= @user.dispname %></h2>
  <%= image_tag 'profile_pic.png' %>
  <p class="profileText">
    <span class="profileNote">Email:</span>
    <%= @user.email %>
  </p>
  <p class="profileText">
    <span class="profileNote">Full name:</span>
    <%= "#{@user.firstname} #{@user.lastname}" %>
  </p>
</div>
<div id="profile_posts">
  <div>
    <h2 class="profileTitle">Questions (<%= @user.questions.count %>)</h2>
    <hr>
    <% @user.questions.each do |que| %>
      <p class="profileText">
        <span class="profileVotes"><%= que.votes %></span>
        <%= link_to add_dots(que.title, 70), que %>
      </p>
    <% end %>
  </div>
  <div>
    <h2 class="profileTitle">Answers (<%= @user.answers.count %>)</h2>
    <hr>
    <% @user.answers.each do |ans| %>
      <p class="profileText">
        <span class="profileVotes"><%= ans.votes %></span>
        <%= link_to add_dots(ans.content, 70), ans.question %>
      </p>
    <% end %>
  </div>
</div>